# DATA UNDERSTANDING

## Load Dataset

In [3]:
import pandas as pd

# Baca file .dta
file_path = "../Dataset/Kontekstual DM/DM2019_kepesertaan.dta"  # Ganti dengan path file Anda
dm = pd.read_stata(file_path)

# Menampilkan beberapa baris pertama dari dataset
dm.head()

,PSTV01,PSTV02,PSTV03,PSTV04,PSTV05,PSTV06,PSTV07,PSTV08,PSTV09,PSTV10,PSTV11,PSTV12,PSTV13,PSTV14,PSTV15,PSTV16,PSTV17,PSTV18
0,45243428,45243428,1959-10-11,PESERTA,PEREMPUAN,KAWIN,KELAS I,PPU,ACEH,PIDIE,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,ACEH,PIDIE,11.468968,2020,AKTIF,NaN
1,356470819,356470819,1965-12-31,PESERTA,LAKI-LAKI,KAWIN,KELAS I,PPU,ACEH,KOTA BANDA ACEH,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,ACEH,KOTA BANDA ACEH,9.863322,2020,AKTIF,NaN
2,72280409,375793382,1964-08-03,ISTRI,PEREMPUAN,CERAI,KELAS I,BUKAN PEKERJA,SUMATERA UTARA,BATU BARA,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,SUMATERA UTARA,BATU BARA,8.487743,2020,AKTIF,NaN
3,88501975,88501975,1959-10-02,PESERTA,PEREMPUAN,KAWIN,KELAS I,PPU,SUMATERA UTARA,ASAHAN,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,SUMATERA UTARA,ASAHAN,10.726228,2020,MENINGGAL,2019.0
4,94870095,310527655,1947-01-01,SUAMI,LAKI-LAKI,KAWIN,KELAS I,BUKAN PEKERJA,SUMATERA BARAT,PESISIR SELATAN,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,SUMATERA BARAT,PESISIR SELATAN,10.539836,2020,AKTIF,NaN

In [4]:
dm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143496 entries, 0 to 143495
Data columns (total 18 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   PSTV01  143496 non-null  int32
 1   PSTV02  143496 non-null  int32
 2   PSTV03  143496 non-null  datetime64[ns]
 3   PSTV04  143496 non-null  category
 4   PSTV05  143496 non-null  category
 5   PSTV06  143496 non-null  category
 6   PSTV07  143496 non-null  category
 7   PSTV08  143496 non-null  category
 8   PSTV09  143496 non-null  category
 9   PSTV10  143496 non-null  category
 10  PSTV11  143496 non-null  category
 11  PSTV12  143496 non-null  category
 12  PSTV13  143496 non-null  category
 13  PSTV14  143496 non-null  category
 14  PSTV15  143496 non-null  float32
 15  PSTV16  143496 non-null  int16
 16  PSTV17  143496 non-null  category
 17  PSTV18  10268 non-null   float64
dtypes: category(12), datetime64[ns](1), float32(1), float64(1), int16(1), int32(2)
memory usage: 6.1 MB

In [5]:
import pandas as pd

# Baca file .dta
file_path = "../Dataset/Kontekstual DM/DM2020_kepesertaan.dta"  # Ganti dengan path file Anda
dm1 = pd.read_stata(file_path)

# Menampilkan beberapa baris pertama dari dataset
dm1.head()

,PSTV01,PSTV02,PSTV03,PSTV04,PSTV05,PSTV06,PSTV07,PSTV08,PSTV09,PSTV10,PSTV11,PSTV12,PSTV13,PSTV14,PSTV15,PSTV16,PSTV17,PSTV18
0,66897393,66897393,1955-12-31,PESERTA,LAKI-LAKI,CERAI,KELAS II,PPU,ACEH,PIDIE,SWASTA,KLINIK PRATAMA,ACEH,PIDIE,11.318326,2020,AKTIF,NaN
1,36947751,36947751,1957-01-01,PESERTA,LAKI-LAKI,KAWIN,KELAS I,BUKAN PEKERJA,ACEH,KOTA BANDA ACEH,SWASTA,DOKTER UMUM,ACEH,KOTA BANDA ACEH,1.850896,2020,AKTIF,NaN
2,58468881,58468881,1959-06-15,PESERTA,PEREMPUAN,KAWIN,KELAS I,BUKAN PEKERJA,ACEH,KOTA LANGSA,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,ACEH,KOTA LANGSA,7.597364,2020,AKTIF,NaN
3,67318251,67318251,1977-11-11,PESERTA,LAKI-LAKI,KAWIN,KELAS II,PPU,ACEH,KOTA LHOKSEUMAWE,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,ACEH,KOTA LHOKSEUMAWE,6.003162,2020,AKTIF,NaN
4,80155656,80155656,1961-12-31,PESERTA,PEREMPUAN,CERAI,KELAS I,PPU,ACEH,BIREUEN,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,ACEH,BIREUEN,11.383931,2020,AKTIF,NaN

In [6]:
dm1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143496 entries, 0 to 143495
Data columns (total 18 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   PSTV01  143496 non-null  int32
 1   PSTV02  143496 non-null  int32
 2   PSTV03  143496 non-null  datetime64[ns]
 3   PSTV04  143496 non-null  category
 4   PSTV05  143496 non-null  category
 5   PSTV06  143496 non-null  category
 6   PSTV07  143496 non-null  category
 7   PSTV08  143496 non-null  category
 8   PSTV09  143496 non-null  category
 9   PSTV10  143496 non-null  category
 10  PSTV11  143496 non-null  category
 11  PSTV12  143496 non-null  category
 12  PSTV13  143496 non-null  category
 13  PSTV14  143496 non-null  category
 14  PSTV15  143496 non-null  float32
 15  PSTV16  143496 non-null  int16
 16  PSTV17  143496 non-null  category
 17  PSTV18  10268 non-null   float64
dtypes: category(12), datetime64[ns](1), float32(1), float64(1), int16(1), int32(2)
memory usage: 6.1 MB

In [7]:
import pandas as pd

# Baca file .dta
file_path = "../Dataset/Kontekstual DM/DM2021_kepesertaan.dta"  # Ganti dengan path file Anda
dm2 = pd.read_stata(file_path)

# Menampilkan beberapa baris pertama dari dataset
dm2.head()

,PSTV01,PSTV02,PSTV03,PSTV04,PSTV05,PSTV06,PSTV07,PSTV08,PSTV09,PSTV10,PSTV11,PSTV12,PSTV13,PSTV14,PSTV15,PSTV16,PSTV17,PSTV18
0,66897393,66897393,1955-12-31,PESERTA,LAKI-LAKI,CERAI,KELAS II,PPU,ACEH,PIDIE,SWASTA,KLINIK PRATAMA,ACEH,PIDIE,11.318326,2021,AKTIF,NaN
1,36947751,36947751,1957-01-01,PESERTA,LAKI-LAKI,KAWIN,KELAS I,BUKAN PEKERJA,ACEH,KOTA BANDA ACEH,SWASTA,DOKTER UMUM,ACEH,KOTA BANDA ACEH,1.850896,2021,AKTIF,NaN
2,58468881,58468881,1959-06-15,PESERTA,PEREMPUAN,KAWIN,KELAS I,BUKAN PEKERJA,ACEH,KOTA LANGSA,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,ACEH,KOTA LANGSA,7.597364,2021,AKTIF,NaN
3,67318251,67318251,1977-11-11,PESERTA,LAKI-LAKI,KAWIN,KELAS II,PPU,ACEH,KOTA LHOKSEUMAWE,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,ACEH,KOTA LHOKSEUMAWE,6.003162,2021,AKTIF,NaN
4,80155656,80155656,1961-12-31,PESERTA,PEREMPUAN,CERAI,KELAS I,PPU,ACEH,BIREUEN,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,ACEH,BIREUEN,11.383931,2021,AKTIF,NaN

In [8]:
dm2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143496 entries, 0 to 143495
Data columns (total 18 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   PSTV01  143496 non-null  int32
 1   PSTV02  143496 non-null  int32
 2   PSTV03  143496 non-null  datetime64[ns]
 3   PSTV04  143496 non-null  category
 4   PSTV05  143496 non-null  category
 5   PSTV06  143496 non-null  category
 6   PSTV07  143496 non-null  category
 7   PSTV08  143496 non-null  category
 8   PSTV09  143496 non-null  category
 9   PSTV10  143496 non-null  category
 10  PSTV11  143496 non-null  category
 11  PSTV12  143496 non-null  category
 12  PSTV13  143496 non-null  category
 13  PSTV14  143496 non-null  category
 14  PSTV15  143496 non-null  float32
 15  PSTV16  143496 non-null  int16
 16  PSTV17  143496 non-null  category
 17  PSTV18  17679 non-null   float64
dtypes: category(12), datetime64[ns](1), float32(1), float64(1), int16(1), int32(2)
memory usage: 6.1 MB

In [ ]:
## Dataset Kepesertaan

Untuk dataset Kepersertaan 2019-2021 library pandas diimpor untuk mengelola data, kemudian file Kepersertaan 2019-2021 dimuat ke dalam DataFrame dm. Dataset Kepersertaan 2019-2021 mencakup data kepesertaan JKN-KIS tahun 2019-2021, termasuk informasi penting seperti nomor peserta (identifikasi unik untuk setiap peserta), tanggal lahir, jenis kelamin, status perkawinan, hubungan keluarga, dan tempat tinggal (provinsi dan kabupaten/kota). Kolom-kolom ini memungkinkan analisis demografi peserta untuk memahami profil populasi yang terdaftar pada tahun tersebut.
Selanjutnya, menampilkan struktur data dm menggunakan dm.info(), yang memberikan informasi tentang jumlah baris, tipe data, serta keberadaan nilai kosong. Ini penting untuk memastikan bahwa data telah dikumpulkan dengan benar dan siap digunakan untuk analisis lebih lanjut.
Berikut penjelasan tiap kolom dari dataset Kepersertaan 2019-2021 : 
- PSTV01: Nomor Peserta – Identifikasi unik untuk peserta.
- PSTV02: Nomor kedua untuk identifikasi, mungkin terkait dengan keperluan internal atau tambahan identifikasi.
- PSTV03: Tanggal lahir peserta – Informasi tentang kapan peserta lahir.
- PSTV04: Hubungan dalam keluarga – Menunjukkan status peserta dalam keluarga, seperti "PESERTA", "ISTRI", "SUAMI".
- PSTV05: Jenis kelamin – Apakah peserta berjenis kelamin "LAKI-LAKI" atau "PEREMPUAN".
- PSTV06: Status perkawinan – Status pernikahan peserta seperti "KAWIN" atau "CERAI".
- PSTV07: Kelas premi – Menunjukkan tingkat layanan yang diikuti oleh peserta, seperti "KELAS I".
- PSTV08: Segmentasi peserta – Kategori peserta seperti "PPU" (Pekerja Penerima Upah), "BUKAN PEKERJA".
- PSTV09: Provinsi tempat tinggal – Provinsi di mana peserta tinggal, misalnya "ACEH", "SUMATERA UTARA".
- PSTV10: Kabupaten/Kota tempat tinggal – Menunjukkan kabupaten/kota peserta, seperti "PIDIE", "KOTA BANDA ACEH".
- PSTV11: Pemerintah penyedia layanan – Informasi tentang pihak penyedia, misalnya "PEMERINTAH KABUPATEN/KOTA".
- PSTV12: Jenis fasilitas kesehatan – Contohnya "PUSKESMAS".
- PSTV13: Provinsi fasilitas kesehatan – Provinsi tempat faskes tersebut berada.
- PSTV14: Kabupaten/Kota fasilitas kesehatan – Informasi kabupaten/kota dari faskes.
- PSTV15: Bobot – Angka yang menunjukkan bobot data untuk keperluan analisis statistik.
- PSTV16: Tahun data terakhir diperbarui – Tahun terakhir di mana data peserta diperbarui, seperti "2020".
- PSTV17: Status aktif peserta – Menunjukkan apakah peserta masih "AKTIF" atau "MENINGGAL".
- PSTV18: Tahun tertentu yang mungkin menunjukkan tahun kejadian atau status tertentu (kolom ini mungkin berisi data numerik atau bisa kosong).

In [9]:
import pandas as pd

file_path = "../Dataset/Kontekstual DM/DM2021_fktpkapitasi.dta"
dm3 = pd.read_stata(file_path, convert_categoricals=False)
dm3.head()

,PSTV01,PSTV02,PSTV15,FKP02,FKP03,FKP04,FKP05,FKP06,FKP07,FKP08,...,FKP14A,FKP15,FKP15A,FKP16,FKP17,FKP18,FKP19,FKP20,FKP21,FKP22
0,12380560,12380560,13.364630,1687160334,2021-11-10,2021-11-10,31,3174,3,1,...,,9999,9999,98,9998,98,98,98,98,2
1,288452470,78043385,8.494392,1457720536,2021-02-26,2021-02-26,17,1702,3,1,...,,9999,9999,98,9998,98,98,98,98,2
2,337885189,337885189,13.472825,1732989007,2021-12-08,2021-12-08,31,3175,3,1,...,,9999,9999,98,9998,98,98,98,98,2
3,2783323,2783323,12.233603,1464029376,2021-03-03,2021-03-03,32,3276,3,1,...,,9999,9999,98,9998,98,98,98,98,2
4,99122276,6688304,6.842236,1646802901,2021-09-28,2021-09-28,52,5272,3,1,...,,9999,9999,98,9998,98,98,98,98,2

In [10]:
dm3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188324 entries, 0 to 1188323
Data columns (total 26 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   PSTV01  1188324 non-null  int32
 1   PSTV02  1188324 non-null  int32
 2   PSTV15  1188324 non-null  float32
 3   FKP02   1188324 non-null  object
 4   FKP03   1188324 non-null  datetime64[ns]
 5   FKP04   1188324 non-null  datetime64[ns]
 6   FKP05   1188324 non-null  int8
 7   FKP06   1188324 non-null  int16
 8   FKP07   1188324 non-null  int8
 9   FKP08   1188324 non-null  int8
 10  FKP09   1188324 non-null  int8
 11  FKP10   1188324 non-null  int8
 12  FKP11   1188324 non-null  int8
 13  FKP12   1188324 non-null  int8
 14  FKP13   1188324 non-null  int8
 15  FKP14   1188324 non-null  int16
 16  FKP14A  1188324 non-null  object
 17  FKP15   1188324 non-null  object
 18  FKP15A  1188324 non-null  object
 19  FKP16   1188324 non-null  int8
 20  FKP17   1188324 non-null  int16
 21  FKP18   1188324 non-null  int8
 22  FKP19   1188324 non-null  int8
 23  FKP20   1188324 non-null  int8
 24  FKP21   1188324 non-null  int16
 25  FKP22   1188324 non-null  int8
dtypes: datetime64[ns](2), float32(1), int16(4), int32(2), int8(13), object(4)
memory usage: 91.8+ MB

In [ ]:
## Dataset fktpkapitasi

Untuk data pelayanan di FKTP dengan model kapitasi tahun 2021 dimuat ke dalam DataFrame dm3 dari file DM2021_fktpkapitasi.dta. Dataset ini mencakup informasi seperti nomor kunjungan, diagnosis ICD-10, jenis layanan, serta pola rujukan. Data ini berguna untuk menganalisis efektivitas pelayanan kesehatan yang diberikan melalui model pembayaran kapitasi.
Selanjutnya, menampilkan informasi dari dm3 menggunakan dm3.info(), yang memvalidasi struktur data pelayanan di FKTP dan memastikan bahwa data siap untuk dianalisis.
Berikut penjelasan tiap kolom dari dataset fktpkapitasi: 
- PSTV01: Nomor peserta yang unik digunakan untuk identifikasi peserta dalam dataset.
- PSTV02: Nomor tambahan atau identifikasi lain yang mungkin relevan dengan peserta.
- PSTV15: Bobot data untuk keperluan analisis statistik, menunjukkan nilai pentingnya data tersebut.
- FKP02: ID unik kunjungan atau entitas terkait pelayanan kesehatan di FKTP.
- FKP03: Tanggal awal pelayanan medis yang diterima oleh peserta.
- FKP04: Tanggal akhir pelayanan medis, menunjukkan durasi layanan.
- FKP05: Usia peserta pada saat layanan diberikan, dicatat dalam tahun.
- FKP06: Kode diagnosis atau indikator lain yang digunakan dalam layanan medis.
- FKP07: Kode atau angka yang mungkin terkait dengan jenis layanan atau prosedur.
- FKP08: Indikator terkait jumlah kunjungan atau frekuensi layanan.
- FKP14A: Kode tambahan yang kemungkinan digunakan untuk klasifikasi layanan atau diagnosis.
- FKP15: Kode atau angka yang mungkin menggambarkan kondisi atau status tertentu dalam layanan.
- FKP15A: Informasi tambahan tentang klasifikasi layanan atau prosedur medis.
- FKP16: Kode yang dapat merujuk pada status layanan atau hasil kunjungan.
- FKP17: Indikator lain yang mungkin digunakan untuk menggambarkan hasil layanan atau status peserta.
- FKP18: Kode yang bisa menunjukkan jenis tindakan medis tertentu.
- FKP19: Angka yang menggambarkan detail tambahan dalam prosedur atau layanan medis.
- FKP20: Indikator terkait jenis layanan yang diberikan kepada peserta.
- FKP21: Kode atau angka yang terkait dengan klasifikasi layanan lanjutan.
- FKP22: Status atau hasil akhir yang berkaitan dengan kunjungan peserta.

In [11]:
import pandas as pd

# Baca file .dta
file_path = "../Dataset/Kontekstual DM/DM2021_fktpnonkapitasi.dta"  # Ganti dengan path file Anda
dm4 = pd.read_stata(file_path)

# Menampilkan beberapa baris pertama dari dataset
dm4.head()

,PSTV01,PSTV02,PSTV15,PNK02,PNK03,PNK04,PNK05,PNK06,PNK07,PNK08,...,PNK12,PNK13,PNK13A,PNK14,PNK15,PNK16,PNK17,PNK18,PNK19,PNK20
0,88204825,88204825,6.755007,203960321P000052,2021-03-13,2021-03-16,2021-03-16,NUSA TENGGARA BARAT,LOMBOK TIMUR,SWASTA,...,PBI APBN,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,Rawat Inap di R. Perawatan Biasa,540000,540000,0.0,NaN
1,24034617,72462276,12.832207,185630321P001651,2021-03-28,2021-03-28,2021-03-30,SULAWESI SELATAN,LUWU,PEMERINTAH KABUPATEN/KOTA,...,PBI APBN,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,Rawat Inap di R. Perawatan Biasa,240000,240000,0.0,NaN
2,17391573,417758463,13.106908,46631021P000693,2021-10-11,2021-10-14,2021-10-14,JAWA BARAT,BANDUNG,PEMERINTAH KABUPATEN/KOTA,...,PBI APBN,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,Rawat Inap di R. Perawatan Biasa,600000,600000,0.0,NaN
3,60560444,60560444,12.762736,325900321P000146,2021-03-17,2021-03-21,2021-03-21,JAWA TENGAH,SRAGEN,SWASTA,...,PBI APBN,A09 Other gastroenteritis and colitis of infec...,A09,A09,Diarrhoea and gastroenteritis of presumed infe...,Rawat Inap di R. Perawatan Biasa,640000,640000,0.0,NaN
4,291346266,291346266,13.404066,460570621P000056,2021-06-13,2021-06-16,2021-06-16,ACEH,ACEH UTARA,SWASTA,...,PPU,A09 Other gastroenteritis and colitis of infec...,A09,A09,Diarrhoea and gastroenteritis of presumed infe...,Rawat Inap di R. Perawatan Biasa,525000,525000,0.0,NaN

In [12]:
dm4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1702 entries, 0 to 1701
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PSTV01  1702 non-null   int32
 1   PSTV02  1702 non-null   int32
 2   PSTV15  1702 non-null   float32
 3   PNK02   1702 non-null   object
 4   PNK03   1702 non-null   datetime64[ns]
 5   PNK04   1702 non-null   datetime64[ns]
 6   PNK05   1702 non-null   datetime64[ns]
 7   PNK06   1702 non-null   category
 8   PNK07   1702 non-null   category
 9   PNK08   1702 non-null   category
 10  PNK09   1702 non-null   category
 11  PNK10   1702 non-null   category
 12  PNK11   1702 non-null   category
 13  PNK12   1702 non-null   category
 14  PNK13   1702 non-null   category
 15  PNK13A  1702 non-null   object
 16  PNK14   1702 non-null   object
 17  PNK15   1702 non-null   object
 18  PNK16   1702 non-null   category
 19  PNK17   1702 non-null   int32
 20  PNK18   1702 non-null   int32
 21  PNK19   1394 non-null   float32
 22  PNK20   1368 non-null   float64
dtypes: category(9), datetime64[ns](3), float32(2), float64(1), int32(4), object(4)
memory usage: 174.7+ KB

In [13]:
import pandas as pd

# Baca file .dta
file_path = "../Dataset/Kontekstual DM/DM2021_fkrtl.dta"  # Ganti dengan path file Anda
dm5 = pd.read_stata(file_path)

# Menampilkan beberapa baris pertama dari dataset
dm5.head()

,PSTV01,PSTV02,PSTV15,FKP02,FKL02,FKL03,FKL04,FKL05,FKL06,FKL07,...,FKL39,FKL40,FKL41,FKL42,FKL43,FKL44,FKL45,FKL46,FKL47,FKL48
0,50886719,50886719,12.507828,,414390221V002006,2021-02-20,2021-02-20,RIAU,KOTA PEKANBARU,POLRI,...,,0,,,0,,,0,184300,184300
1,70972186,6871133,13.055749,,380700421V000216,2021-04-07,2021-04-08,KALIMANTAN TIMUR,KOTA SAMARINDA,TNI AD,...,,0,,,0,,,0,2578800,2578800
2,31874094,71865092,7.740489,,385450421V006571,2021-04-19,2021-04-19,JAWA TENGAH,KOTA SURAKARTA,Swasta,...,,0,,,0,,,0,193800,193800
3,87945875,87945875,7.734398,,206900221V006045,2021-02-28,2021-03-03,ACEH,ACEH TENGAH,Pemerintah kab/kota,...,,0,,,0,,,0,2705800,2705800
4,384677503,384677503,2.777775,,447120121V000468,2021-01-29,2021-02-01,SUMATERA SELATAN,KOTA PRABUMULIH,Swasta,...,,0,,,0,,,0,2174700,2174700

In [14]:
dm5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 826641 entries, 0 to 826640
Data columns (total 55 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   PSTV01  826641 non-null  int32
 1   PSTV02  826641 non-null  int32
 2   PSTV15  826641 non-null  float32
 3   FKP02   826641 non-null  object
 4   FKL02   826641 non-null  object
 5   FKL03   826641 non-null  datetime64[ns]
 6   FKL04   826641 non-null  datetime64[ns]
 7   FKL05   826641 non-null  category
 8   FKL06   826641 non-null  category
 9   FKL07   826641 non-null  category
 10  FKL08   826641 non-null  category
 11  FKL09   826641 non-null  category
 12  FKL10   826641 non-null  category
 13  FKL11   826641 non-null  category
 14  FKL12   826641 non-null  category
 15  FKL13   826641 non-null  category
 16  FKL14   826641 non-null  category
 17  FKL15   826641 non-null  category
 18  FKL15A  826641 non-null  object
 19  FKL16   826641 non-null  object
 20  FKL16A  826641 non-null  object
 21  FKL17   826641 non-null  category
 22  FKL17A  826641 non-null  object
 23  FKL18   826641 non-null  object
 24  FKL18A  826641 non-null  object
 25  FKL19   826641 non-null  object
 26  FKL19A  826641 non-null  object
 27  FKL20   826641 non-null  category
 28  FKL21   826641 non-null  category
 29  FKL22   826641 non-null  int8
 30  FKL23   826641 non-null  category
 31  FKL25   826641 non-null  category
 32  FKL26   826641 non-null  category
 33  FKL27   826641 non-null  category
 34  FKL28   826641 non-null  category
 35  FKL29   826641 non-null  category
 36  FKL30   826641 non-null  object
 37  FKL31   826641 non-null  category
 38  FKL32   826641 non-null  int32
 39  FKL33   826641 non-null  object
 40  FKL34   826641 non-null  int32
 41  FKL35   826641 non-null  object
 42  FKL36   826641 non-null  object
 43  FKL37   826641 non-null  int32
 44  FKL38   826641 non-null  object
 45  FKL39   826641 non-null  object
 46  FKL40   826641 non-null  int32
 47  FKL41   826641 non-null  object
 48  FKL42   826641 non-null  object
 49  FKL43   826641 non-null  int32
 50  FKL44   826641 non-null  object
 51  FKL45   826641 non-null  object
 52  FKL46   826641 non-null  int32
 53  FKL47   826641 non-null  int32
 54  FKL48   826641 non-null  int32
dtypes: category(21), datetime64[ns](2), float32(1), int32(10), int8(1), object(20)
memory usage: 194.1+ MB

In [15]:
import pandas as pd

# Baca file .dta
file_path = "../Dataset/Kontekstual DM/DM2021_fkrtldxsekunder.dta"  # Ganti dengan path file Anda
dm6 = pd.read_stata(file_path)

# Menampilkan beberapa baris pertama dari dataset
dm6.head()

              FKL02 FKL24 FKL24A                                   FKL24B
0  100080121V000024  E119    E11             E11 Type 2 diabetes mellitus
1  100080121V000024   I10    I10     I10 Essential (primary) hypertension
2  100080121V000024  I693    I69  I69 Sequelae of cerebrovascular disease
3  100080121V000078  E119    E11             E11 Type 2 diabetes mellitus
4  100080121V000078  I693    I69  I69 Sequelae of cerebrovascular disease

In [16]:
dm6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1202910 entries, 0 to 1202909
Data columns (total 4 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   FKL02   1202910 non-null  object
 1   FKL24   1202910 non-null  object
 2   FKL24A  1202910 non-null  object
 3   FKL24B  1202910 non-null  object
dtypes: object(4)
memory usage: 36.7+ MB

## Main Dataset (Primary Data)

In [18]:
fktpk = dm3
fktpk.head()

,PSTV01,PSTV02,PSTV15,FKP02,FKP03,FKP04,FKP05,FKP06,FKP07,FKP08,...,FKP14A,FKP15,FKP15A,FKP16,FKP17,FKP18,FKP19,FKP20,FKP21,FKP22
0,12380560,12380560,13.364630,1687160334,2021-11-10,2021-11-10,31,3174,3,1,...,,9999,9999,98,9998,98,98,98,98,2
1,288452470,78043385,8.494392,1457720536,2021-02-26,2021-02-26,17,1702,3,1,...,,9999,9999,98,9998,98,98,98,98,2
2,337885189,337885189,13.472825,1732989007,2021-12-08,2021-12-08,31,3175,3,1,...,,9999,9999,98,9998,98,98,98,98,2
3,2783323,2783323,12.233603,1464029376,2021-03-03,2021-03-03,32,3276,3,1,...,,9999,9999,98,9998,98,98,98,98,2
4,99122276,6688304,6.842236,1646802901,2021-09-28,2021-09-28,52,5272,3,1,...,,9999,9999,98,9998,98,98,98,98,2

Fokus proyek ini berfokus pada dataset fktp kapitasi ini, karena bussines understanding dari penelitian ini mengarah pada prediksi kunjungan sakit ataupun sehat pada peserta, maka dataset fktp kapitasi ini memuat sebuah atribut target (FKP22) yang memuat jenis kunjungan sakit atau sehat. Dengan demikian fokus proyek ini mengarah pada prediksi kunjungan sakit atau sekat di fktp kapitasi. Dataset lainnya akan menjadi data pendukung untuk memudahkan dan menambahkan informasi penting lainnya untuk mendukung penyampaian informasi hasil prediksi yang lebih baik.